name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v2
        with:
          version: 0.16.0
      - run: zig fmt --check .

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v2
        with:
          version: 0.16.0
      - run: zig build test -Doptimize=Debug
      - run: zig build test -Doptimize=ReleaseFast
      - run: zig build run-example -Doptimize=Debug

  consumer-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v2
        with:
          version: 0.16.0
      - run: zig build run -Doptimize=Debug
        working-directory: integration/consumer
      - run: zig build run -Doptimize=ReleaseFast
        working-directory: integration/consumer
